services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: pipeline
      MYSQL_ROOT_PASSWORD: password
  app:
    image: openjdk:8
    volumes:
      - $WORKSPACE:/project
    links:
      - db
